### ISSUE TITLE
文章中使用代码块，在文章元数据中显示出了文章中不包含的数字

### ISSUE THREAD

**Issue by Mai-icy** [Dreamer-Paul/Hingle#7]
文章中使用代码块，在下方文章元数据`post-meta`中会显示出代码块前面的1234567...

**Comment by Dreamer-Paul** [comment]
请提供具体的代码和复现过程？

**Comment by Mai-icy** [comment]
以下是我的markdown文件内容（部分）：
```markdown
#### Undigraph头文件

# 加权图

## 数据类型

因为继承体系，我们将图分为有权图和无权图，又各自分为有向和无向。

### 有权图

依旧使用邻接表来实现。

基类头文件

```c++
class BaseGraph
{
public:
    BaseGraph(int v) : vertex_num(v){};
    int V() const { return vertex_num; };
    int E() const { return edge_num; };

protected:
    int vertex_num;
    int edge_num = 0;
};

class BaseWeightedGraph : public BaseGraph
{
public:
    BaseWeightedGraph(int v) : BaseGraph(v) {}
    virtual void addEdge(int v, int w, double weight) = 0;
};
```

显示效果
![example](https://user-images.githubusercontent.com/62082723/217755325-cc709374-9813-43a1-aace-ed86d00c21a8.PNG)

**Comment by Dreamer-Paul** [comment]
俺看了一下，这个问题疑似是 Hexo 本身的问题，需要进一步提交排查～

**Comment by Dreamer-Paul** [comment]
经过排查后发现是 Highlight 的代码行数渲染所致，初步想到一个方案，就是使用 Prism 替代 Highlight 实现代码高亮，另外再修改样式，支持一下代码行数的展示，应该就可以完美解决这个问题。接下来我再提供下修复的方案～

**Comment by Dreamer-Paul** [comment]
这个问题已经修复，方便的话更新试试，没问题的话你就可以关掉了

**Comment by Mai-icy** [comment]
我替换了新的主题文件，但是问题似乎并没有解决。
文章内的效果是这样
![IG_IS%SWOS~)I$@(I9M@ B](https://user-images.githubusercontent.com/62082723/218300547-7edd9673-7af6-444f-a7d8-3704940c801a.png)
代码没有高亮并且外面还是显示123456
![image](https://user-images.githubusercontent.com/62082723/218300550-f9c5e20f-a3cb-40a3-8141-811b6567271d.png)

我替换了主题文件，检查对应了新commit的代码
以下是我的hexo版本：（不知道是否有关）
![image](https://user-images.githubusercontent.com/62082723/218300603-8cc6f5bf-9c22-4572-90b5-e01563788b1d.png)

**Comment by Dreamer-Paul** [comment]
> 

看上去你没关闭 Highlight，忘了说了，Hexo 的 `_config.yml` 要先修改，之后再执行 `hexo clean`。参考下我的 [配置](https://github.com/Dreamer-Paul/Hingle-Demo/blob/master/_config.yml)

**Comment by Mai-icy** [comment]
根据其修改了
```
highlight:
  enable: false  #  原本为true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true  #  原本为false
  preprocess: true
  line_number: true
  tab_replace: ''
```
生效了，问题已经解决。

非常感谢，您的主题十分好看
用起来非常舒服😋
